import { v4 as uuid } from 'uuid';

const getFields = (userType) => {
  const fields = [
    {
      id: uuid(),
      tag: 'heading',
      label: 'Persnoal Info',
    },
    {
      id: uuid(),
      label: 'First Name',
      tag: 'input',
      name: 'firstName',
      placeholder: 'First name',
      type: 'text',
      rules: [{ required: true }],
      initialValue: '',
    },
    {
      id: uuid(),
      label: 'Last Name',
      tag: 'input',
      name: 'lastName',
      placeholder: 'Last name',
      type: 'text',
      rules: [{ required: true }],
      initialValue: '',
    },
    {
      id: uuid(),
      label: 'ID',
      tag: 'input',
      name: 'idNo',
      placeholder: 'ID',
      type: 'number',
      rules: [{ required: true }],
      initialValue: '',
    },
    {
      id: uuid(),
      label: 'Expiry Date of id',
      tag: 'date',
      name: 'idNoExpiryDate',
      placeholder: 'Expiry Date of id',
      rules: [{ required: true }],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Selelct ID type',
      tag: 'select',
      name: 'idNoTypeId',
      placeholder: 'Selelct ID type',
      type: 'drop-down',
      getURL: '/idNoTypes',
      postURL: '/idNoTypes',
      enableAddItem: true,
      rules: [{ required: true }],
      items: ['resident', 'citizen'],
      initialValue: '',
    },
    {
      id: uuid(),
      label: 'ID Status',
      tag: 'input',
      name: 'idNoStatus',
      placeholder: 'ID Status',
      type: 'text',
      rules: [{ required: true }],
      dependency: 'idNoExpiryDate',
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Date of Birthday',
      tag: 'date',
      name: 'birthdayDate',
      placeholder: 'Date of Birthday',
      rules: [{ required: true }],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Age',
      tag: 'input',
      name: 'age',
      placeholder: 'Age',
      type: 'text',
      rules: [{ required: true }],
      dependency: 'birthdayDate',
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Nationality',
      tag: 'select',
      name: 'nationalityId',
      placeholder: 'Nationality',
      type: 'drop-down',
      getURL: '/nationality',
      postURL: '/nationality',
      enableAddItem: true,
      rules: [],
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Name of Sponsor',
      tag: 'input',
      name: 'sponsor',
      placeholder: 'Name of Sponsor',
      type: 'text',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Mobile',
      tag: 'input',
      name: 'phoneNumber',
      placeholder: 'Mobile',
      type: 'text',
      rules: [{ required: true }],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Email',
      tag: 'input',
      name: 'email',
      placeholder: 'Email',
      type: 'text',
      rules: [{ required: true, type: 'email' }],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Country',
      tag: 'select',
      name: 'countryId',
      placeholder: 'Country',
      type: 'drop-down',
      rules: [{ required: true }],
      getURL: '/countries',
      postURL: '/countries',
      enableAddItem: true,
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'City',
      tag: 'select',
      name: 'cityId',
      placeholder: 'City',
      type: 'drop-down',
      getURL: '/cities',
      postURL: '/cities',
      enableAddItem: true,
      rules: [{ required: true }],
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Language',
      tag: 'languages',
      name: 'language',
      placeholder: 'Language',
      type: 'drop-down',
      enableAddItem: true,
      rules: [],
      getURL: '/languages',
      postURL: '/languages',
      items: [1, 2, 3],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'password',
      placeholder: 'Password.',
      type: 'password',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'upload',
      name: 'idPhoto',
      label: 'Upload ID',
    },
    {
      id: uuid(),
      tag: 'upload',
      name: 'licensePhoto',
      label: 'Upload license',
    },
    {
      // for driver
      id: uuid(),
      tag: 'upload',
      name: 'driverPhoto',
      label: 'Upload photo of driver',
    },
    {
      tag: 'heading',
      label: 'Work Info',
    },
    {
      id: uuid(),
      label: 'Staff Type',
      tag: 'select',
      name: 'staffTypeId',
      placeholder: 'Staff Type',
      type: 'drop-down',
      rules: [{ required: true }],
      items:
        userType === '1'
          ? [{ id: '9', name: 'manager' }, { id: '6', name: 'driver' }]
          : userType === '2'
            ? [{ id: '7', name: 'manager' }, { id: '6', name: 'driver' }]
            : userType === '7' || userType === '9'
              ? [{ id: '6', name: 'driver' }]
              : [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Licenses Expire',
      tag: 'date',
      name: 'licensesExpire',
      placeholder: 'Licenses Expire',
      rules: [{ required: true }],
      initialValue: undefined,
      dependency: 'staffTypeId',
      dependencyValue: '6',
    },
    {
      id: uuid(),
      label: 'Licenses Status',
      tag: 'input',
      name: 'licensesStatus',
      placeholder: 'Licenses Status',
      type: 'text',
      rules: [{ required: true }],
      dependency: ['staffTypeId', 'licensesExpire'],
      dependencyValue: '6',
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Type of licenses',
      tag: 'select',
      name: 'licenseTypeId',
      placeholder: 'Type of licenses',
      type: 'drop-down',
      enableAddItem: true,
      getURL: '/licenseTypes',
      postURL: '/licenseTypes',
      rules: [{ required: true }],
      items: [],
      dependency: 'staffTypeId',
      dependencyValue: '6',
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Effictive Date',
      tag: 'date',
      name: 'effectiveDate',
      placeholder: 'Effictive Date',
      rules: [{ required: true }],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Work Location',
      tag: 'select',
      name: 'locationId',
      placeholder: 'Location',
      type: 'drop-down',
      enableAddItem: true,
      getURL: '/locations',
      postURL: '/locations',
      rules: [{ required: true }],
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Daily Time Work',
      tag: 'select',
      name: 'dailyTimeWorkId',
      placeholder: 'Daily Time Work',
      type: 'drop-down',
      enableAddItem: true,
      getURL: '/dailytimeworks',
      postURL: '/dailytimeworks',
      rules: [{ required: true }],
      items: ['8 hours', '12 hours'],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Medical insurance company',
      tag: 'select',
      name: 'medicalInsuranceCompanyId',
      placeholder: 'Medical insurance company',
      type: 'drop-down',
      enableAddItem: true,
      getURL: '/medicalInsuranceCompanies',
      postURL: '/medicalInsuranceCompanies',
      rules: [],
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Medical insurance expiry date',
      tag: 'date',
      name: 'medicalInsuranceExpiryDate',
      placeholder: 'Medical insurance expiry date',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Medical Insurance Fees',
      tag: 'input',
      name: 'medicalInsuranceFees',
      placeholder: 'Medical Insurance Fees',
      type: 'text',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Type of shift',
      tag: 'select',
      name: 'shiftTypeId',
      placeholder: 'Type of shift',
      type: 'drop-down',
      getURL: '/shiftTypes',
      postURL: '/shiftTypes',
      enableAddItem: true,
      rules: [{ required: true }],
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Type of staff',
      tag: 'select',
      name: 'typeofstaffId',
      placeholder: 'Type of staff',
      getURL: '/typeofstaff',
      postURL: '/typeofstaff',
      labelValue: true,
      type: 'drop-down',
      enableAddItem: true,
      rules: [{ required: true }],
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Monthly salary',
      tag: 'input',
      name: 'monthlySalary',
      placeholder: 'Monthly salary',
      type: 'text',
      rules: [{ required: true }],
      initialValue: '',
      dependency: 'typeofstaffId',
      dependencyValue: 'Permenant',
    },
    // {
    //   id: uuid(),
    //   label: 'Currency',
    //   tag: 'select',
    //   name: 'currency',
    //   placeholder: 'Choose Currency',
    //   // getURL: '/typeofstaff',
    //   // postURL: '/typeofstaff',
    //   type: 'drop-down',
    //   rules: [{ required: true }],
    //   items: ['$', '€', '£', '¥'],
    //   initialValue: undefined,
    // },
    {
      id: uuid(),
      label: 'Rate Per Day',
      tag: 'input',
      name: 'rate',
      placeholder: 'Rate Per Day',
      type: 'text',
      rules: [{ required: true }],
      initialValue: '',
      dependency: 'typeofstaffId',
      dependencyValue: 'outsource',
    },
    {
      id: uuid(),
      label: 'Driver Availability',
      tag: 'select',
      name: 'driverAvailabilityId',
      placeholder: 'Driver Availability',
      type: 'drop-down',
      enableAddItem: true,
      getURL: '/driverAvailability',
      postURL: '/driverAvailability',
      rules: [{ required: true }],
      labelValue: true,
      items: ['active', 'inactive'],
      initialValue: undefined,
    },
    {
      id: uuid(),
      label: 'Reason',
      tag: 'select',
      name: 'unavailabilityReasonId',
      placeholder: 'Reason',
      type: 'drop-down',
      enableAddItem: true,
      rules: [{ required: true }],
      getURL: '/unavailabilityReasons',
      postURL: '/unavailabilityReasons',
      items: [],
      initialValue: undefined,
      dependency: 'driverAvailabilityId',
      dependencyValue: 'inactive',
    },
    {
      id: uuid(),
      label: 'Note / Description',
      tag: 'input',
      name: 'note',
      placeholder: 'Note / Description',
      type: 'text',
      rules: [],
      initialValue: '',
    },
    // {
    //   id: uuid(),
    //   label: 'Top Driver',
    //   tag: 'select',
    //   name: 'topDriver',
    //   placeholder: 'Top Driver',
    //   type: 'drop-down',
    //   enableAddItem: false,
    //   rules: [{ required: true }],
    //   items: ['true', 'false'], // get data from API.
    //   initialValue: undefined,
    // },
  ];

  const initialValues = fields.reduce((values, cuuField) => {
    let initialValuesObj = values;

    initialValuesObj = {
      ...initialValuesObj,
      [cuuField.name]: cuuField.initialValue,
    };

    return initialValuesObj;
  }, {});

  return {
    initialValues,
    fields,
  };
};

export default getFields;
