import { v4 as uuid } from 'uuid';

const fields = [
  {
    id: uuid(),
    tag: 'input',
    name: 'firstName',
    placeholder: 'Name',
    type: 'text',
    rules: [],
    initialValue: undefined,
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'companyName',
    placeholder: 'Company Name',
    type: 'text',
    rules: [],
    initialValue: undefined,
  },
  {
    id: uuid(),
    tag: 'select',
    name: 'clientTypeId',
    placeholder: 'Client Type',
    type: 'drop-down',
    enableAddItem: false,
    getURL: '/clientTypes',
    postURL: '/clientTypes',
    rules: [],
    items: ['individual', 'Corporate'],
    initialValue: undefined,
  },
  {
    id: uuid(),
    tag: 'select',
    name: 'countryId',
    placeholder: 'Country',
    type: 'drop-down',
    enableAddItem: false,
    getURL: '/countries',
    postURL: '/countries',
    rules: [{ required: true }],
    items: [],
    initialValue: undefined,
  },
  {
    id: uuid(),
    tag: 'select',
    name: 'cityId',
    placeholder: 'City',
    type: 'drop-down',
    enableAddItem: false,
    getURL: '/cities',
    postURL: '/cities',
    rules: [{ required: true }],
    items: [],
    initialValue: undefined,
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'street',
    placeholder: 'street',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'district',
    placeholder: 'District',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'landLine',
    placeholder: 'Land line',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'fax',
    placeholder: 'Fax',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'email',
    placeholder: 'Email',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'website',
    placeholder: 'Web site',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'vat',
    placeholder: 'VAT NO',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'cr',
    placeholder: 'CR NO',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'contactPerson',
    placeholder: 'Contact Person',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'username',
    placeholder: 'Username.',
    type: 'text',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'password',
    placeholder: 'Password.',
    type: 'password',
    rules: [],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'phoneNumber',
    placeholder: 'Mobile phone.',
    type: 'text',
    rules: [{ required: true }],
    initialValue: '',
  },
  {
    id: uuid(),
    tag: 'input',
    name: 'personEmail',
    placeholder: 'Person Email',
    type: 'text',
    rules: [],
    initialValue: '',
  },
];

const initialValues = fields.reduce((values, cuuField) => {
  let initialValuesObj = values;
  initialValuesObj = {
    ...initialValuesObj,
    [cuuField.name]: cuuField.initialValue,
  };
  return initialValuesObj;
}, {});

export {
  initialValues,
  fields,
};
