import { v4 as uuid } from 'uuid';

import arrayNumbers from '../../utils/getData';

const getFields = (userType) => {
  const fields = [
    {
      id: uuid(),
      tag: 'select',
      name: 'vehicleNameId',
      placeholder: 'Vehicle Name',
      type: 'drop-down',
      enableAddItem: true,
      rules: [],
      getURL: '/vehicleNames',
      postURL: '/vehicleNames',
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'vehicleTypeId',
      placeholder: 'Vehicle type',
      type: 'drop-down',
      enableAddItem: true,
      getURL: '/vehicleTypes',
      postURL: '/vehicleTypes',
      rules: [],
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'fleetTypeId',
      placeholder: 'Fleet Type',
      type: 'drop-down',
      enableAddItem: true,
      rules: [],
      getURL: '/fleetTypes',
      postURL: '/fleetTypes',
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'yearModel',
      placeholder: 'Year Model',
      type: 'number',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'vehicleColorId',
      placeholder: 'Color',
      type: 'drop-down',
      enableAddItem: true,
      rules: [],
      getURL: '/vehicleColors',
      postURL: '/vehicleColors',
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'plateNo',
      placeholder: 'Plate No.',
      type: 'text',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'locationId',
      placeholder: 'Location',
      type: 'drop-down',
      enableAddItem: true,
      rules: [],
      getURL: '/locations',
      postURL: '/locations',
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'passengerCount',
      placeholder: 'Passenger Count',
      type: 'drop-down',
      rules: [],
      items: arrayNumbers(1, 100),
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'bigLuggage',
      placeholder: 'Big Luggage',
      type: 'drop-down',
      rules: [],
      items: arrayNumbers(1, 100),
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'smallLuggage',
      placeholder: 'Small Luggage',
      type: 'drop-down',
      rules: [],
      items: arrayNumbers(1, 100),
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'licensesNo',
      placeholder: 'Licenses No.',
      type: 'text',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'date',
      name: 'expireLicenses',
      placeholder: 'Expiry Date of Licenses',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'taxRoad',
      type: 'text',
      placeholder: 'Tax Road',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'date',
      name: 'expireTaxRoad',
      placeholder: 'Expiry Date of Tax Road',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'motNumber',
      type: 'text',
      placeholder: 'Mot Number',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'date',
      name: 'expireMot',
      placeholder: 'Expiry Date of Mot Number',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'carAvailabilityId',
      placeholder: 'Car Availability',
      type: 'drop-down',
      enableAddItem: true,
      rules: [],
      getURL: '/CarAvailability',
      postURL: '/CarAvailability',
      items: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'ownership',
      placeholder: 'Ownership',
      type: 'drop-down',
      rules: [],
      items: ['own fleet', 'outsource'],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'ownershipName',
      type: 'text',
      placeholder: 'Ownership Name',
      rules: [],
      initialValue: '',
      dependency: 'ownership',
      dependencyValue: 'outsource',
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'driverId',
      placeholder: 'Driver',
      type: 'drop-down',
      rules: [{ required: userType === '2' }],
      getURL: '/drivers',
      items: ['driver 1', 'driver 2'],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'carOptions',
      placeholder: 'carOptions',
      type: 'drop-down',
      enableAddItem: true,
      rules: [],
      getURL: '/carOptions',
      postURL: '/carOptions',
      items: [],
      initialValue: undefined,
      mulitple: true,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'note',
      placeholder: 'Note / Description',
      type: 'text',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'upload',
      name: 'carPhoto',
      label: 'Upload photo of car',
    },
    {
      id: uuid(),
      tag: 'upload',
      name: 'insurancePhoto',
      label: 'Upload photo of insurance',
    },
    {
      id: uuid(),
      tag: 'upload',
      name: 'licensePhoto',
      label: 'Upload photo of License',
    },
    {
      id: uuid(),
      tag: 'upload',
      name: 'motPhoto',
      label: 'Upload photo of MOT',
    },
    {
      id: uuid(),
      tag: 'upload',
      name: 'taxRoadPhoto',
      label: 'Upload photo of Tax road',
    },
    // {
    //   id: uuid(),
    //   tag: 'select',
    //   name: 'carStatus',
    //   placeholder: 'Car Status',
    //   type: 'drop-down',
    //   enableAddItem: true, // Will just be in the edit
    //   rules: [],
    //   items: ['statement of revenue', 'selling a car', 'total loss', 'in maintenance'],
    //   initialValue: undefined,
    // },
    {
      id: uuid(),
      tag: 'date',
      name: 'acquisitionData',
      placeholder: 'Date of Acquisition',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'acquisitionCost',
      placeholder: 'Acquisition Cost',
      prefix: '$',
      type: 'number',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'usedLife',
      placeholder: 'Used Life',
      type: 'drop-down',
      rules: [],
      items: arrayNumbers(1, 100),
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'monthlyDepreciation',
      placeholder: 'Monthly Depreciation',
      type: 'text',
      rules: [],
      prefix: '$',
      dependency: ['acquisitionCost', 'usedLife'], // equation by usedLife and acquisitionCost
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'insuranceFeesCost',
      placeholder: 'Cost of insurance fees',
      type: 'text',
      prefix: '$',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'insurancePolicyNo',
      placeholder: 'Car Insurance Number',
      type: 'text',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'date',
      name: 'expireInsurance',
      placeholder: 'Expiry Date of Insurance',
      rules: [],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'insuranceCompany',
      placeholder: 'Company of insurance',
      type: 'text',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'insuranceDeductible',
      placeholder: 'Deductible of insurance',
      type: 'text',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'insuranceAmount',
      placeholder: 'Ammount of insurance',
      type: 'text',
      prefix: '$',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'insurancePercentage',
      placeholder: 'Percentage of insurance',
      type: 'text',
      prefix: '%',
      rules: [],
      initialValue: '',
    },
    {
      id: uuid(),
      tag: 'select',
      name: 'insuranceTypeId',
      placeholder: 'Insurance Type',
      type: 'drop-down',
      enableAddItem: true,
      rules: [],
      getURL: '/insuranceTypes',
      postURL: '/insuranceTypes',
      items: ['Third party', 'Full Comprehensive Insurance'],
      initialValue: undefined,
    },
    {
      id: uuid(),
      tag: 'input',
      name: 'carOwner',
      placeholder: 'Car Owner',
      type: 'text',
      rules: [],
      initialValue: '',
    },
  ];
  const initialValues = fields.reduce((values, cuuField) => {
    let initialValuesObj = values;
    initialValuesObj = {
      ...initialValuesObj,
      [cuuField.name]: cuuField.initialValue,
    };
    return initialValuesObj;
  }, {});
  return {
    initialValues,
    fields,
  };
};

export default getFields;
